// Code generated by protoc-gen-go. DO NOT EDIT.

package muamalahmatrix

import (
	"context"
	"fmt"
	"io"
	"log"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// MuamalahMatrixClient is the client API for MuamalahMatrix service.
type MuamalahMatrixClient struct {
	cc grpc.ClientConn
}

func NewMuamalahMatrixClient(cc grpc.ClientConn) MuamalahMatrixClient {
	return MuamalahMatrixClient{cc}
}

func (c MuamalahMatrixClient) MuamalahMatrix(ctx context.Context, req *MuamalahMatrixRequest) (*MuamalahMatrixResponse, error) {
	out, err := c.cc.Invoke(ctx, "/muamalahmatrix.MuamalahMatrix/MuamalahMatrix", req)
	if err != nil {
		return nil, err
	}
	var resp MuamalahMatrixResponse
	if err := resp.Unmarshal(out); err != nil {
		return nil, err
	}
	return &resp, nil
}

// MuamalahMatrixServer is the server API for MuamalahMatrix service.
type MuamalahMatrixServer struct{}

func (s MuamalahMatrixServer) MuamalahMatrix(ctx context.Context, req *MuamalahMatrixRequest) (*MuamalahMatrixResponse, error) {
	// Implement the MuamalahMatrix logic here
	return &MuamalahMatrixResponse{Message: "Hello, " + req.UserId}, nil
}

func RegisterMuamalahMatrixServer(srv *grpc.Server, ss MuamalahMatrixServer) {
	srv.RegisterService(&MuamalahMatrix_ServiceDesc, ss)
}

func _ MuamalahMatrix_MuamalahMatrix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MuamalahMatrixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MuamalahMatrixServer).MuamalahMatrix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/muamalahmatrix.MuamalahMatrix/MuamalahMatrix",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MuamalahMatrixServer).MuamalahMatrix(ctx, req.(*MuamalahMatrixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MuamalahMatrix_serviceDesc = grpc.ServiceDesc{
	ServiceName: "muamalahmatrix.MuamalahMatrix",
	HandlerType: (*MuamalahMatrixServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MuamalahMatrix",
			Handler:    _MuamalahMatrix_MuamalahMatrix_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "muamalah-matrix-api.proto",
}
